name = "NonconvexNOMAD"
uuid = "2385ff6c-83fd-4e6c-afbd-4e7983621e3f"
authors = ["Mohamed Tarek <mohdibntarek@gmail.com> and contributors"]
version = "0.1.1"

[deps]
NOMAD = "02130f1c-4665-5b79-af82-ff1385104aa0"
NonconvexCore = "035190e5-69f1-488f-aaab-becca2889735"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
NOMAD = "2.2"
NonconvexCore = "1.1.1"
Parameters = "0.12"
Reexport = "1"
Zygote = "0.6"
julia = "1"

[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["LinearAlgebra", "Test"]
